### ISSUE TITLE
Won't install - Windows

### ISSUE THREAD

**Issue by Patnetpatnet** [dronekit/dronekit-la#111]
Following instructions: "Install the tool by running the installer/extracting the files" after unzipping and then running the .exe file Windows 7 get a quick flash of a black window box and then nothing happens. No interface. Please advise.

**Comment by peterbarker** [comment]
On Tue, 27 Nov 2018, Patnetpatnet wrote:

> Following instructions: "Install the tool by running the
> installer/extracting the files" after unzipping and then running the .exe
> file Windows 7 get a quick flash of a black window box and then nothing
> happens. No interface. Please advise.

The .exe is a command-line tool only.

**Comment by Patnetpatnet** [comment]
Thanks.
