### ISSUE TITLE
Publically releasable example logs

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-la#19]
Would be good to source some example test logs that can be used for demonstration purposes in the docs. 

Currently I am using logs from LogAnalyser - but I'd prefer logs that exhaustively test what this tool can do!

**Comment by peterbarker** [comment]
The only commit which adds logs is this:

https://github.com/dronekit/dronekit-la-testdata/commit/c7b97dec13ba6d01deda1db53bacf7454ad8ea5f

... and it has a commit message indicating they are my logs.  I should have explicitly said I was happy for them to be distributed.

**Comment by mrpollo** [comment]
fair enough, then we are ok to share

**Comment by peterbarker** [comment]
dronekit-la-testdata is publically-available data
