### ISSUE TITLE
Rename and improve the Brownout test

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-la#27]
The Brownout test provides an ambiguous report for analysis. 

The reason for this is that its main check is whether the log was truncated, but there are several possible reasons for truncation, including brownout, running out of memory for logging, or failure of the logging subsystem for other reasons. We can do better analysis of the log to confirm the likely cause is brownout, but this won't be canonical.

The proposal is two part.

* Perform analysis on the voltage change prior to end-of-log. A rapid voltage drop prior to log truncation is indicative of brownout.
* Rename test to "Log Truncation". This is more accurate. It might be best to add this test in parallel for first version.

**Comment by peterbarker** [comment]
This was done.
