### ISSUE TITLE
The -p (pure flag) not fit for purpose

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-la#29]
No one will use pure flag because next time the tool gets updated the field they depend on is removed - forcing them to go back to the "all old fields" to get what they need ... or immediately update to the new versions.

What we want is a mechanism that allows users to not have to do anything as we update the tool, but to be able to easily update if they want. Effectively some method to specify a desired output protocol. Ideally   with some hints on what changes they need to make.

I'm sure you can come up with a good method. A few ideas ...

a) flag "deprecated list" which lists all deprecated fields, and flag "removefield" with values of all, or comma separated list of the fields they want removed. That way they may get "excess fields" in new version, but they'll never lose a field they want.
b) flag "fields" which they can specify set of fields to display  - with alias v1, v2, v3, v4, latest or whatever for a particular protocol version. Perhaps ability to lists fields in an alias or NOT in an alias?
In this case if they set v4 they always get v4. 
c) -o v1, v2, v3 etc for each version. We encourage people to use the last version documented.

**Comment by peterbarker** [comment]
I think this means that the current Pure is OK.

**Comment by hamishwillee** [comment]
Yes, that's fine :-)
