### ISSUE TITLE
Update build number in source to 0.4 for release and give me the release .deb

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-la#70]
This is still beta release so just rev the build number by 0.1 to 0.4.

I will also need a copy of the .deb file in order to include it in the release. If you have a Windows installer binary that would be good too.

My docs are going  to be updated to say that this build is 0.4, so if you don't do this before release there will be a mismatch.

**Comment by peterbarker** [comment]
We blew all the way through to 0.5!
